[2023-12-11 21:44:38,762] INFO _log() L96    * Restarting with stat - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 21:44:45,900] ERROR log_exception() L825  Exception on /amostra [POST] - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\flask\app.py L825 
Traceback (most recent call last):
  File "Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "Z:\ENEM\exemplo_mvp\api\app.py", line 63, in predict
    modelo = Model.carrega_modelo(ml_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\ENEM\exemplo_mvp\api\model\modelo.py", line 12, in carrega_modelo
    model = pickle.load(open(path, 'rb'))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'ManhattanDistance' on <module 'sklearn.metrics._dist_metrics' from 'Z:\\ENEM\\exemplo_mvp\\api\\env\\Lib\\site-packages\\sklearn\\metrics\\_dist_metrics.cp311-win_amd64.pyd'>
[2023-12-11 21:44:45,913] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 21:44:45] "[35m[1mPOST /amostra HTTP/1.1[0m" 500 - - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 21:51:24,140] INFO _log() L96   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.0.0.126:5000 - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 21:51:24,142] INFO _log() L96   [33mPress CTRL+C to quit[0m - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 21:51:24,145] INFO _log() L96    * Restarting with stat - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 21:51:31,486] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 21:51:31] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 21:51:31,562] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 21:51:31] "GET /openapi/ HTTP/1.1" 200 - - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 21:51:31,911] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 21:51:31] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 21:51:31,933] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 21:51:31] "[36mGET /openapi/static/images/redoc.svg HTTP/1.1[0m" 304 - - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 21:51:31,999] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 21:51:31] "[36mGET /openapi/static/images/rapidoc.svg HTTP/1.1[0m" 304 - - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 21:51:33,029] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 21:51:33] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 21:51:33,053] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 21:51:33] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 21:51:33,057] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 21:51:33] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 21:51:33,062] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 21:51:33] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 21:51:33,349] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 21:51:33] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 21:51:44,311] ERROR log_exception() L825  Exception on /amostra [POST] - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\flask\app.py L825 
Traceback (most recent call last):
  File "Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "Z:\ENEM\exemplo_mvp\api\app.py", line 69, in predict
    Hardness=form.Hardness,
             ^^^^^^^^^^^^^
  File "Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\pydantic\main.py", line 761, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'AmostraSchema' object has no attribute 'Hardness'
[2023-12-11 21:51:44,323] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 21:51:44] "[35m[1mPOST /amostra HTTP/1.1[0m" 500 - - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 21:56:38,435] INFO _log() L96    * Detected change in 'Z:\\ENEM\\exemplo_mvp\\api\\app.py', reloading - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 21:56:38,682] INFO _log() L96    * Restarting with stat - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 21:56:46,340] ERROR log_exception() L825  Exception on /amostra [POST] - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\flask\app.py L825 
Traceback (most recent call last):
  File "Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "Z:\ENEM\exemplo_mvp\api\app.py", line 69, in predict
    hardness=form.Hardness,
             ^^^^^^^^^^^^^
  File "Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\pydantic\main.py", line 761, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'AmostraSchema' object has no attribute 'Hardness'
[2023-12-11 21:56:46,346] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 21:56:46] "[35m[1mPOST /amostra HTTP/1.1[0m" 500 - - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 22:00:27,516] INFO _log() L96    * Detected change in 'Z:\\ENEM\\exemplo_mvp\\api\\app.py', reloading - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 22:00:27,748] INFO _log() L96    * Restarting with stat - call_trace=Z:\ENEM\exemplo_mvp\api\env\Lib\site-packages\werkzeug\_internal.py L96  
